### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by b0nd** [sensepost/wadi#1]
I believe following is typo:
else if (evt[1] == 'ProgrssEvent') {

"
else if (evt[1] == 'ProgrssEvent') {
            returnArray = returnArray.concat('var '+e+'= new PorgressEvent("'+evt[0]+'",{ "bubbles":'+randbool()+', "cancelable":'+randbool()+', "lengthComputable":'+randbool()+', "loaded":'+rint(ra(INT_NUMS))+', "total":'+rint(ra(INT_NUMS))+'})')
        }
"

**Comment by ssherei** [comment]
Yes indeed thank you for that. Will fix it.

Thanks

**Comment by b0nd** [comment]
Cool. 
Here goes few more with spell of "compact"

['comapct',[function() { return randbool() },''],'high']

And hats-off to you guys for coding stuff in that minute level. Phew...I would die doing that. Gr8 job guys.

**Comment by ssherei** [comment]
Thanks again really appreciate  your input and help. :D

Thanks,
Saif

**Comment by b0nd** [comment]
["fontSize",["xx-small","x-small","small","medium","large","x-large","xx-large","larger","smaller",posdistanceValue1,posdistanceValue1,"inherit"]],

Did you mean some other array the next time (posdistanceValue1)?
Same is for font-Size.

Cheers!

**Comment by b0nd** [comment]
['flex-basis',[posdistanceValueflex,'initial','inherit','auto']],

I think it should be posdistanceValueflex() (same goes for other array flexBasis) 

Cheers!

**Comment by b0nd** [comment]
["height",[posdistanceValue2,posdistanceValue2,.... 
Not sure is that deliberate.

Cheers!

**Comment by ssherei** [comment]
Hello  b0nd,
Happy new year. This is deliberate as to increase the chances of calling posdistancevalue2 whenever height is fuzzed. 

Thanks,

Saif

**Comment by ssherei** [comment]
If it is posdistancevalueflex() it would be called each time the testcase generator is instantiated even without flex-basis being fuzzed, which increase processing and overhead so in that case we either use this notation or function() {posdistancevalueflex()} so it is only called when requested. I hope i make sense bro :D

Thanks

**Comment by ssherei** [comment]
Hey b0nd,

Thanks allot for your efforts man i really appreciate it. The repetition is just to increase the chances that  this function will be called instead of the other values of the property when fuzzed. Does this answer your question or further clarification is needed ??

Thanks,
Saif

**Comment by b0nd** [comment]
Hi Saif,

Thanks for your prompt replies. Yes, I got it now.
To be honest, I know how much pain it is to write such extensive
dictionaries and beautiful randoms.js. So, I am going through your code and
picking up the stuff which could improve my fuzzer code. And in return, I
am trying to report bugs so that they could be rectified in your production
fuzzer code.

Thanks for making it open source buddy! It needs guts.

Cheers!
b0nd

On Mon, Jan 4, 2016 at 6:08 PM, Saif El Sherei notifications@github.com
wrote:

> Hey b0nd,
> 
> Thanks allot for your efforts man i really appreciate it. The repetition
> is just to increase the chances that this function will be called instead
> of the other values of the property when fuzzed. Does this answer your
> question or further clarification is needed ??
> 
> Thanks,
> Saif
> 
> Sent from my iPhone
> 
> > On 3 Jan 2016, at 23:04, b0nd notifications@github.com wrote:
> > 
> > ["fontSize",["xx-small","x-small","small","medium","large","x-large","xx-large","larger","smaller",posdistanceValue1,posdistanceValue1,"inherit"]],
> > 
> > Did you mean some other array the next time (posdistanceValue1)?
> > Same is for font-Size.
> > 
> > Cheers!
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sensepost/wadi/issues/1#issuecomment-168582278.

## 

Security Researcher
Co-owner of Ethical Hacking forum www.garage4hackers.com

**Comment by ssherei** [comment]
Hey Man,

Thank you for your help dude really appreciate it. What you are doing is what i was hoping to happen when i release it opensource. Seriously bro thanks again for your kind words and help. Let me know if i can be of any help anytime man. 

Thanks,

Saif

**Comment by b0nd** [comment]
'ruby '+ra(['full-width','proportional-width']+" "+ra(['jis78','jis83','jis90','jis04','simplified','traditional']))
or should it be:
'ruby '+ra(['full-width','proportional-width'])+" "+ra(['jis78','jis83','jis90','jis04','simplified','traditional'])

**Comment by b0nd** [comment]
['text-under-line-position',['auto','under','inherit']]
or should it be:
['text-underline-position',['auto','under','inherit']]

**Comment by ssherei** [comment]
Thanks as always b0nd
