### ISSUE TITLE
Function doesn't return

### ISSUE THREAD

**Issue by b0nd** [sensepost/wadi#10]
In "Canvas2d.js", following function prepares 'returnString' but doesn't return anything though it's been called at few places.

strokeStyleFunc = function() {
    var returnString = ''
    switch(rint(3)) {
        case 0:
            returnString += 'ctx.createLinearGradient('+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+')'
            break;
        case 1:
            returnString += 'ctx.createRadialGradient('+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+','+ra([rint(ra(INT_NUMS)),floatValue()])+')'
            break;
        case 2:
            returnString += 'ctx.createPattern(img,"'+ra(['repeat','repeat-x','repeat-y','no-repeat',''])+'")'
            break;
    }
}

**Comment by ssherei** [comment]
Thanks updated.
