### ISSUE TITLE
Same name HTMLTableHeaderCellElementInterface for "TH" & "THEAD"

### ISSUE THREAD

**Issue by b0nd** [sensepost/wadi#5]
Hi,
Noticed in IE.js module.
HTMLTableHeaderCellElementInterface has been defined twice; once for 'TH' and once for 'THEAD' and var ElementArray = [] has also got 2 entries for it.
I believe name of one shall be changed else you never know which one is getting execution chance.

Cheers!

**Comment by ssherei** [comment]
yupp thanks c
