### ISSUE TITLE
Typo - comma instead of '+'

### ISSUE THREAD

**Issue by b0nd** [sensepost/wadi#8]
Hi,

['setRangeText',[function() {return rint(2) ? '"'+string(rint(STR_NUM))+'"':'""'},function() {return rint(2) ? '"'+string(rint(STR_NUM))+'",'+rint(ra(INT_NUMS))+","+rint(ra(INT_NUMS)):'"'+string(rint(STR_NUM))+'",'+randoms()+","+randoms()},function() {return rint(2) ? '"'+string(rint(STR_NUM))+'",'+rint(ra(INT_NUMS))+","+rint(ra(INT_NUMS))+","+ra(['"select"','"start"','"end"','"preserve"','""']):'"'+string(rint(STR_NUM))+'",'+randoms()+","+randoms()+",",ra(['"select"','"start"','"end"','"preserve"','""'])},''],'high'],

If you notice the last part of it -> 
(+",",ra(['"select"','"start"','"end"','"preserve"','""'])},''],'high'],)

I think it should have been:
(+","+ra(['"select"','"start"','"end"','"preserve"','""'])},''],'high'],)

**Comment by ssherei** [comment]
Thanks b0nd
