### ISSUE TITLE
FILTER_ACCEPT missing

### ISSUE THREAD

**Issue by b0nd** [sensepost/wadi#9]
['filter',[function() {return "{acceptNode:"+ra(['NodeFilter.FILTER_REJECT','NodeFilter.FILTER_SKIP','NodeFilter.FILTER_REJECT'

I believe, instead of two FILTER_REJECT, one should be FILTER_ACCEPT.

Cheers!

**Comment by ssherei** [comment]
Thanks Agaim b0nd :D
